# Generated by Django 2.2.6 on 2020-01-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('gadgets', 'Gadgets'), ('machine learning', 'Machine Learning'), ('events', 'Events'), ('not', 'Not')], default='not', max_length=20),
        ),
    ]
